index:
    path: /
    controller: App\Controller\IndexController::index

registration:
    path: /registration
    controller: App\Controller\RegistrationController:registration

app_login:
    path: /login
    controller: App\Controller\SecurityController:login

#ARTICLE------------------------------------------------------------------------------------------------
create_new_article:
    path: /createarticle
    controller: App\Controller\CreateNewArticleController:createNewArticle

show_article:
    path: /article/{article}
    controller: App\Controller\ArticleController:showArticleAndAddAndShowComment

add_favorite:
    path: /addfavorite/{article}
    controller: App\Controller\FavoriteController:addFavoriteArticleForUser