index:
    path: /
    controller: App\Controller\IndexController::index

registration:
    path: /registration
    controller: App\Controller\RegistrationController:registration

app_login:
    path: /login
    controller: App\Controller\SecurityController:login

app_logout:
    path: /logout

#ARTICLE------------------------------------------------------------------------------------------------
create_new_article:
    path: /createarticle
    controller: App\Controller\CreateNewArticleController:createNewArticle

edit_article:
    path: /editarticle/{article}
    controller: App\Controller\EditArticleController:editArticle

show_article:
    path: /article/{article}
    controller: App\Controller\ArticleController:showArticleAndAddAndShowComment

add_favorite:
    path: /addfavorite/{article}
    controller: App\Controller\FavoriteController:addFavoriteArticleForUser


#PROFILE------------------------------------------------------------------------------------------------

view_profile:
    path: /profile/{user}
    controller: App\Controller\ProfileController:viewProfile

view_article_by_id_user:
    path: /profile/article/{user}
    controller: App\Controller\ProfileController:selectArticle


#COMMENT------------------------------------------------------------------------------------------------

edit_comment:
    path: /editcomment/{comment}/{article}
    controller: App\Controller\CommentController:editComment